/**
 * Report Generator Service
 * Generates PDF and JSON reports for clinical reviews
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportData {
  screeningId: string;
  childName: string;
  childAgeMonths: number;
  screeningDate: string;
  doctorName?: string;
  clinicName?: string;
  verificationHash?: string;
  aiAnalysis: {
    riskScore: number | null;
    summary: string | null;
    domainScores: {
      social: number | null;
      fineMotor: number | null;
      language: number | null;
      grossMotor: number | null;
    };
  };
  clinicalAssessment: {
    riskLevel: 'LOW' | 'MODERATE' | 'HIGH' | null;
    diagnosis: string | null;
    recommendations: string | null;
    domainScores: {
      social: number | null;
      fineMotor: number | null;
      language: number | null;
      grossMotor: number | null;
    };
  };
  reviewedBy: string | null;
  reviewedAt: string | null;
}

/**
 * Generate JSON report
 */
export function generateJSONReport(data: ReportData): string {
  const report = {
    reportType: 'Clinical Screening Report',
    generatedAt: new Date().toISOString(),
    screening: {
      id: data.screeningId,
      childName: data.childName,
      childAgeMonths: data.childAgeMonths,
      screeningDate: data.screeningDate,
    },
    aiAnalysis: data.aiAnalysis,
    clinicalAssessment: data.clinicalAssessment,
    reviewedBy: data.reviewedBy,
    reviewedAt: data.reviewedAt,
  };

  return JSON.stringify(report, null, 2);
}

/**
 * Generate text report (for PDF generation)
 */
export function generateTextReport(data: ReportData): string {
  const lines: string[] = [];

  lines.push('='.repeat(60));
  lines.push('CLINICAL SCREENING REPORT');
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(`Screening ID: ${data.screeningId}`);
  lines.push(`Child Name: ${data.childName}`);
  lines.push(`Age: ${data.childAgeMonths} months`);
  lines.push(`Screening Date: ${new Date(data.screeningDate).toLocaleDateString()}`);
  lines.push('');
  lines.push('-'.repeat(60));
  lines.push('AI ANALYSIS');
  lines.push('-'.repeat(60));
  lines.push('');
  
  if (data.aiAnalysis.riskScore !== null) {
    lines.push(`Overall Risk Score: ${data.aiAnalysis.riskScore}/100`);
  }
  
  if (data.aiAnalysis.summary) {
    lines.push('');
    lines.push('Summary:');
    lines.push(data.aiAnalysis.summary);
  }
  
  lines.push('');
  lines.push('Domain Scores:');
  lines.push(`  Personal-Social: ${data.aiAnalysis.domainScores.social ?? 'N/A'}/100`);
  lines.push(`  Fine Motor: ${data.aiAnalysis.domainScores.fineMotor ?? 'N/A'}/100`);
  lines.push(`  Language: ${data.aiAnalysis.domainScores.language ?? 'N/A'}/100`);
  lines.push(`  Gross Motor: ${data.aiAnalysis.domainScores.grossMotor ?? 'N/A'}/100`);
  
  lines.push('');
  lines.push('-'.repeat(60));
  lines.push('CLINICAL ASSESSMENT');
  lines.push('-'.repeat(60));
  lines.push('');
  
  if (data.clinicalAssessment.riskLevel) {
    lines.push(`Clinical Risk Level: ${data.clinicalAssessment.riskLevel}`);
  }
  
  if (data.clinicalAssessment.diagnosis) {
    lines.push(`Final Diagnosis: ${data.clinicalAssessment.diagnosis}`);
  }
  
  lines.push('');
  lines.push('Clinical Domain Scores:');
  lines.push(`  Personal-Social: ${data.clinicalAssessment.domainScores.social ?? 'N/A'}/100`);
  lines.push(`  Fine Motor: ${data.clinicalAssessment.domainScores.fineMotor ?? 'N/A'}/100`);
  lines.push(`  Language: ${data.clinicalAssessment.domainScores.language ?? 'N/A'}/100`);
  lines.push(`  Gross Motor: ${data.clinicalAssessment.domainScores.grossMotor ?? 'N/A'}/100`);
  
  if (data.clinicalAssessment.recommendations) {
    lines.push('');
    lines.push('Recommendations:');
    lines.push(data.clinicalAssessment.recommendations);
  }
  
  lines.push('');
  lines.push('-'.repeat(60));
  if (data.reviewedBy) {
    lines.push(`Reviewed by: ${data.reviewedBy}`);
  }
  if (data.reviewedAt) {
    lines.push(`Review Date: ${new Date(data.reviewedAt).toLocaleDateString()}`);
  }
  lines.push('');
  lines.push('This report was generated by KiddyGuard - Privacy-Preserving Pediatric Screening');
  lines.push('='.repeat(60));

  return lines.join('\n');
}

/**
 * Generate professional PDF report using jsPDF
 */
export function generateProfessionalPDF(data: ReportData): jsPDF {
  const doc = new jsPDF();
  const timestamp = new Date(data.reviewedAt || data.screeningDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // KiddyGuard Indigo color: #4F46E5 (RGB: 79, 70, 229)
  const indigoColor = [79, 70, 229];

  // 1. Header & Branding
  doc.setFillColor(indigoColor[0], indigoColor[1], indigoColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('KIDDYGUARD', 15, 20);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL CLINICAL DEVELOPMENTAL REPORT', 15, 30);

  // 2. Patient & Clinic Info
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT INFORMATION', 15, 50);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${data.childName}`, 15, 58);
  doc.text(`Age: ${data.childAgeMonths} months`, 15, 64);
  doc.text(`Date of Review: ${timestamp}`, 15, 70);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('CLINIC DETAILS', 120, 50);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Pediatrician: ${data.reviewedBy || data.doctorName || 'Dr. Smith'}`, 120, 58);
  doc.text(`Facility: ${data.clinicName || 'KiddyGuard Clinic'}`, 120, 64);

  // 3. Denver II Domain Comparison Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('DEVELOPMENTAL DOMAIN ASSESSMENT', 15, 85);

  const domainLabels: Record<string, string> = {
    social: 'Personal-Social',
    fineMotor: 'Fine Motor',
    language: 'Language',
    grossMotor: 'Gross Motor',
  };

  const tableRows = Object.entries(domainLabels).map(([key, label]) => {
    const aiScore = data.aiAnalysis.domainScores[key as keyof typeof data.aiAnalysis.domainScores] ?? 0;
    const clinicalScore = data.clinicalAssessment.domainScores[key as keyof typeof data.clinicalAssessment.domainScores] ?? 0;
    const status = clinicalScore >= 75 ? 'Pass' : 'Requires Monitoring';
    
    return [
      label,
      `${aiScore}%`,
      `${clinicalScore}%`,
      status,
    ];
  });

  autoTable(doc, {
    startY: 90,
    head: [['Domain', 'AI Analysis', 'Clinical Verdict', 'Status']],
    body: tableRows,
    headStyles: { 
      fillColor: indigoColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    styles: { fontSize: 9 },
  });

  // 4. Clinical Verdict & Recommendations
  const finalY = (doc as any).lastAutoTable.finalY + 15;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('FINAL DIAGNOSIS', 15, finalY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const diagnosis = data.clinicalAssessment.diagnosis || data.clinicalAssessment.riskLevel || 'No diagnosis provided';
  doc.text(diagnosis, 15, finalY + 8, { maxWidth: 180 });

  doc.setFont('helvetica', 'bold');
  doc.text('RECOMMENDATIONS', 15, finalY + 25);
  doc.setFont('helvetica', 'normal');
  const recommendations = data.clinicalAssessment.recommendations || 'No specific recommendations provided.';
  doc.text(recommendations, 15, finalY + 33, { maxWidth: 180 });

  // 5. Privacy & Security Footer
  const footerY = 280;
  doc.setDrawColor(200, 200, 200);
  doc.line(15, footerY - 5, 195, footerY - 5);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Privacy-Preserving Payment Verified via Zcash Shielded Pool', 15, footerY);
  
  if (data.verificationHash) {
    doc.text(`Verification Hash: ${data.verificationHash.substring(0, 16)}...`, 15, footerY + 5);
  }
  
  doc.text('This report is digitally signed and encrypted for patient privacy.', 120, footerY);

  return doc;
}

/**
 * Generate PDF report (legacy - returns blob URL)
 * Note: This is kept for backward compatibility
 */
export function generatePDFReport(data: ReportData): Blob {
  const doc = generateProfessionalPDF(data);
  const pdfBlob = doc.output('blob');
  return pdfBlob;
}

/**
 * Download report as file
 */
export function downloadReport(data: ReportData, format: 'json' | 'txt' = 'json'): void {
  let content: string;
  let filename: string;
  let mimeType: string;

  if (format === 'json') {
    content = generateJSONReport(data);
    filename = `clinical-report-${data.screeningId.substring(0, 8)}.json`;
    mimeType = 'application/json';
  } else {
    content = generateTextReport(data);
    filename = `clinical-report-${data.screeningId.substring(0, 8)}.txt`;
    mimeType = 'text/plain';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

